/**
 * Created by rick on 22/05/2014.
 */

// Create some extras data. ~50 values per location id, ranging from 1-50
var extraCountMin = 20,
    extraCountRange = 30,
    extraValMin = 1,
    extraValRange = 49;

var conn = new Mongo();
var db = conn.getDB("ukonline");

var locations = db.Locations.find();//.limit(2);
var doc, extra, count, extraId = 1;

// Remove any current extras
db.Extras.remove();

while (locations.hasNext()) {
    // Get the location object
    doc = locations.next();
    //printjson(doc);

    // How extras for this one?
    count = Math.floor((Math.random() * extraCountRange) + extraCountMin);

    while(count > 0) {
        extra = {
            ExtraID: extraId,
            LocationID: doc.LocationID,
            ExtraValue: Math.floor((Math.random() * extraValRange) + extraValMin)
        };

        db.Extras.save(extra);
        //printjson(extra);

        extraId++;
        count--;
    }
}



db = conn.getDB("metadata");
db.Entities.update({name: 'Locations'}, {
    "name" : "Locations",
    "active" : 1,
    "description" : {
        "shortName" : "Location",
        "namespace" : "Tinder",
        "defaultResourceName" : "Locations",
        "key" : {
            "propertyRef" : {
                "name" : "LocationID"
            }
        },
        "autoGeneratedKeyType" : "Identity",
        "namedConnection" : "tinder.ukonline",
        "listable" : false,
        "dataProperties" : [
            {
                "name" : "LocationID",
                "dataType" : "Int32",
                "isPartOfKey" : true,
                "isNullable" : false,
                "validators" : [
                    {
                        "name" : "integer"
                    }
                ]
            },
            {
                "name" : "Address1",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z0-9- @&,:\\/'\\.\\(\\)]{0,255})$"
                    }
                ]
            },
            {
                "name" : "Address2",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z0-9- @&,:\\/'\\.\\(\\)]{0,255})$"
                    }
                ]
            },
            {
                "name" : "Address3",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z0-9- \\/']{0,255})$"
                    }
                ]
            },
            {
                "name" : "Address4",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z- \\/]{0,255})$"
                    }
                ]
            },
            {
                "name" : "Town",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z- &!'\\.]{2,255})$"
                    }
                ]
            },
            {
                "name" : "PostCode",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "postCode"
                    }
                ]
            },
            {
                "name" : "LookupCountyID",
                "dataType" : "Int32",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "integer"
                    }
                ]
            },
            {
                "name" : "LookupRegionID",
                "dataType" : "Int32",
                "isPartOfKey" : false,
                "isNullable" : false,
                "validators" : [
                    {
                        "name" : "integer"
                    }
                ]
            },
            {
                "name" : "Country",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : false,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z -]{2,255})$"
                    }
                ]
            },
            {
                "name" : "Nation",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "maxLength",
                        "maxLength" : 255
                    },
                    {
                        "name" : "regularExpression",
                        "expression" : "^([a-zA-Z -]{2,255})$"
                    }
                ]
            },
            {
                "name" : "Phone",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "phone"
                    }
                ]
            },
            {
                "name" : "Email",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "emailAddress"
                    }
                ]
            },
            {
                "name" : "Fax",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "phone"
                    }
                ]
            },
            {
                "name" : "Website",
                "dataType" : "String",
                "isPartOfKey" : false,
                "isNullable" : true,
                "validators" : [
                    {
                        "name" : "url"
                    }
                ]
            }
        ],
        "navigationProperties" : [
            {
                "name" : "LookupCountys",
                "entityTypeName" : "LookupCounty:#Tinder",
                "isScalar" : true,
                "associationName" : "Location_LookupCounty",
                "foreignKeyNames" : [
                    "LookupCountyID"
                ]
            },
            {
                "name" : "Extras",
                "entityTypeName" : "Extra:#Tinder",
                "isScalar" : false,
                "associationName" : "Location_Extra",
                "invForeignKeyNames" : [
                    "LocationID"
                ]
            }
        ]
    }
});


db.Entities.save({
    "name" : "Extras",
    "active" : 1,
    "description" : {
        "shortName" : "Extra",
        "namespace" : "Tinder",
        "defaultResourceName" : "Extras",
        "key" : {
            "propertyRef" : {
                "name" : "ExtraID"
            }
        },
        "autoGeneratedKeyType" : "Identity",
        "namedConnection" : "tinder.ukonline",
        "listable" : false,
        "dataProperties" : [
            {
                "name" : "ExtraID",
                "dataType" : "Int32",
                "isPartOfKey" : true,
                "isNullable" : false,
                "validators" : [
                    {
                        "name" : "integer"
                    }
                ]
            },
            {
                "name" : "ExtraValue",
                "dataType" : "Int32",
                "isPartOfKey" : false,
                "isNullable" : false,
                "validators" : [
                    {
                        "name" : "integer"
                    }
                ]
            }
        ],
        "navigationProperties" : [
        ]
    }
});
