/*
* Map reduce version of run.php
*/
var conn = new Mongo();
var db = conn.getDB("ukonline");

var mapFunction = function() {
    var group = Math.floor(this.LookupCountyID / 1000);
    emit('G' + group, 1);
};
var reduceFunction = function(key, values) {
    return Array.sum(values);
};

print('Count:' + db.LookupCountys.find().count());
print('Key: G0 = England, G1 = Scotland, G2 = Wales, G3 = NI');

var mr = db.Locations.mapReduce(
    mapFunction,
    reduceFunction,
    {
        out: { inline: 1 }
    }
);
printjson(mr);
print('Completed');



/*

 db.Entities.update({name: 'Locations'}, {
 "name" : "Locations",
 "active" : 1,
 "description" : {
 "shortName" : "Location",
 "namespace" : "Tinder",
 "defaultResourceName" : "Locations",
 "key" : {
 "propertyRef" : {
 "name" : "LocationID"
 }
 },
 "autoGeneratedKeyType" : "Identity",
 "namedConnection" : "tinder.ukonline",
 "listable" : false,
 "dataProperties" : [
 {
 "name" : "LocationID",
 "dataType" : "Int32",
 "isPartOfKey" : true,
 "isNullable" : false,
 "validators" : [
 {
 "name" : "integer"
 }
 ]
 },
 {
 "name" : "Address1",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z0-9- @&,:\\/'\\.\\(\\)]{0,255})$"
 }
 ]
 },
 {
 "name" : "Address2",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z0-9- @&,:\\/'\\.\\(\\)]{0,255})$"
 }
 ]
 },
 {
 "name" : "Address3",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z0-9- \\/']{0,255})$"
 }
 ]
 },
 {
 "name" : "Address4",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z- \\/]{0,255})$"
 }
 ]
 },
 {
 "name" : "Town",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z- &!'\\.]{2,255})$"
 }
 ]
 },
 {
 "name" : "PostCode",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "postCode"
 }
 ]
 },
 {
 "name" : "LookupCountyID",
 "dataType" : "Int32",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "integer"
 }
 ]
 },
 {
 "name" : "LookupRegionID",
 "dataType" : "Int32",
 "isPartOfKey" : false,
 "isNullable" : false,
 "validators" : [
 {
 "name" : "integer"
 }
 ]
 },
 {
 "name" : "Country",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : false,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z -]{2,255})$"
 }
 ]
 },
 {
 "name" : "Nation",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "maxLength",
 "maxLength" : 255
 },
 {
 "name" : "regularExpression",
 "expression" : "^([a-zA-Z -]{2,255})$"
 }
 ]
 },
 {
 "name" : "Phone",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "phone"
 }
 ]
 },
 {
 "name" : "Email",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "emailAddress"
 }
 ]
 },
 {
 "name" : "Fax",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "phone"
 }
 ]
 },
 {
 "name" : "Website",
 "dataType" : "String",
 "isPartOfKey" : false,
 "isNullable" : true,
 "validators" : [
 {
 "name" : "url"
 }
 ]
 }
 ],
 "navigationProperties" : [
 {
 "name" : "LookupCountys",
 "entityTypeName" : "LookupCounty:#Tinder",
 "isScalar" : true,
 "associationName" : "Location_LookupCounty",
 "foreignKeyNames" : [
 "LookupCountyID"
 ]
 },
 {
 "name" : "Extras",
 "entityTypeName" : "Extra:#Tinder",
 "isScalar" : false,
 "associationName" : "Location_Extra",
 "invForeignKeyNames" : [
 "LocationID"
 ]
 }
 ]
 }
 });


 db.Entities.save({
 "name" : "Extras",
 "active" : 1,
 "description" : {
 "shortName" : "Extra",
 "namespace" : "Tinder",
 "defaultResourceName" : "Extras",
 "key" : {
 "propertyRef" : {
 "name" : "ExtraID"
 }
 },
 "autoGeneratedKeyType" : "Identity",
 "namedConnection" : "tinder.ukonline",
 "listable" : false,
 "dataProperties" : [
 {
 "name" : "ExtraID",
 "dataType" : "Int32",
 "isPartOfKey" : true,
 "isNullable" : false,
 "validators" : [
 {
 "name" : "integer"
 }
 ]
 },
 {
 "name" : "ExtraValue",
 "dataType" : "Int32",
 "isPartOfKey" : false,
 "isNullable" : false,
 "validators" : [
 {
 "name" : "integer"
 }
 ]
 }
 ],
 "navigationProperties" : [
 ]
 }
 });


 */